- name: app setup
  include_role:
    name: common
    tasks_from: app_setup   

- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs
   
- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd   

- name: copying the repo file
  ansible.builtin.copy:
    src: "mongo.repo"
    dest: "/etc/yum.repos.d/mongo.repo"

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present    

- name: check products loaded or not
  ansible.builtin.command: mongosh --host {{MONGODB}} --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output       

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load products  
  ansible.builtin.shell: mongosh --host {{MONGODB}}  < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0          # converting frm string to int        