  - name: disable the default version
    ansible.builtin.command: "dnf module disable nodejs -y"

  - name: enable the version
    ansible.builtin.command: "dnf module enable nodejs:20 -y"  
  
  - name: installing nodejs
    ansible.builtin.package: 
      name: nodejs
      state: present  

  - name: installing dependencies
    community.general.npm:
      path: /app          